### ISSUE TITLE
3rd sdk init in ApplicationBase

### ISSUE THREAD

**Issue by javalue** [googlesamples/android-RuntimePermissions#19]
In my app, I init some 3rd sdk in ApplicationBase, if it need dangerous permission, how deal with it.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
