### ISSUE TITLE
Android Studio Import Issue

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-RuntimePermissions#20]
After cloning I imported the code in Android Studio 2.3.3 But app folder is not showing in Project>Android and also other android specific option like Android Monitor is absent. Build Project not working.

How I imported is as followed. File>New>Import Project>android-RuntimePermissions>build.gradle and then clicked ok

**Comment by Missingiscool** [comment]
I am having a similar issue importing this example into android studios.

**Comment by Missingiscool** [comment]
Gradle sync failed: Could not find com.android.tools.build:gradle:3.0.0.
				Searched in the following locations:
				file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
				file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
				https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.pom
				https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0/gradle-3.0.0.jar
				Required by:
				project :
				Consult IDE log for more details (Help | Show Log) (474ms)

**Comment by Rodrirokr** [comment]
Having this response when trying to build
`Task 'assemble' not found in root project 'android-RuntimePermissions'.`

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
