### ISSUE TITLE
java.lang.NullPointerException:

### ISSUE THREAD

**Issue by Boxerbuzz** [googlesamples/android-RuntimePermissions#21]
Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
