### ISSUE TITLE
Typo in comments...

### ISSUE THREAD

**Issue by fat-tire** [googlesamples/android-RuntimePermissions#5]
Trivial almost not worth mentioning, but given the [layout](https://github.com/googlesamples/android-RuntimePermissions/blob/master/Application/src/main/res/layout/fragment_main.xml#L46), this [comment](https://github.com/googlesamples/android-RuntimePermissions/blob/master/Application/src/main/java/com/example/android/system/runtimepermissions/MainActivity.java#L174) looks to be the result of a copy/paste that wasn't changed.  Should probably read:

```
 * Called when the 'Show and add contacts' button is clicked.
```

**Comment by keyboardsurfer** [comment]
Internal: 26813987

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
