### ISSUE TITLE
ContextCompat checkSelfPermission - not working < API23

### ISSUE THREAD

**Issue by mars3142** [googlesamples/android-RuntimePermissions#6]
The checkSelfPermission in ContextCompat didn't check the API level and crashes below M (API 23).

**Comment by miltomasz** [comment]
Hi,
The same problem here. It just always returns a value as 'permission not granted". I'm testing on targetSdk = 17.

**Comment by johngamarra** [comment]
I have the same issue

**Comment by Ahmed-Mostafa-Ghanayem** [comment]
Runtime Permission is only working for API 23 and above. For previous APIs PERMISSIONs are granted at APPLICATION installation, so you should check for SDK version before checking if PERMISSION is GRANTED or not, you can use this code:
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M){
     // check if permission is granted or not
}

**Comment by keyboardsurfer** [comment]
Internal: 26814360

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
