### ISSUE TITLE
It would be good to have an example of requesting a permission from a fragment. 

### ISSUE THREAD

**Issue by dbachelder** [googlesamples/android-RuntimePermissions#9]
One needs to use fragment.requestPermission instead of ActivityCompat or Activity requestPermission in order for the response to propagate to the fragment correctly.

**Comment by amaresh26** [comment]
ok thx for the info and i will be doing it. By the way this method works fine for me....i have a look into it deeply and make sure if any changes need to be taken.....

**Comment by keyboardsurfer** [comment]
Internal: 26814409

**Comment by sanjaykumarm** [comment]
Yes I am facing the same issue while requesting permissions from fragment itself and specially for v4 fragment.

**Comment by LuYongJin** [comment]
Not Very Mature

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
